# The workflow name
name: Update translations and contributors

# Controls when the workflow will run
on: 
  push:
    branches:
      - main
    paths:
      - "**/translations/**"
      - "**/config/MasterTranslations.xml"
  pull_request:
    branches:
      - main
      - 'TranslationFileHandeling' # for test only
    paths:
      - "**/translations/**"
      - "**/config/MasterTranslations.xml"

# The list of jobs this workflow executes
jobs:
  # Updates the translations
  update_translations:
    name: Update translations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Update translation xml files.
        run: | 
          python -m pip install lxml
          python .github/scripts/update-translations/updateTranslations.py
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated translations

  get_all_files:
    name: Get all files
    runs-on: ubuntu-latest
    needs: [update_translations]
    outputs:
      files: ${{ steps.get-json.outputs.files }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 2
      # Pulls the translation changes from above.
      - name: Pull changes
        run:
          git pull origin
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23
      - name: changed files into json file
        id: get-json
        run: |
          const output = steps.changed-files.outputs.all_changed_file
          console.log(output);
          core.setOutput("files", JSON.stringify(output));

    #  - name: Filter commits of author
    #    id: getcommits
    #    uses: actions/github-script@v6
    #    with:
    #      script: |
    #        const promises = context.payload.commits
    #          .filter(commit => commit.author.username === context.actor)
    #          .map(commit => exec.getExecOutput("git", ["log", "-p", "-1", "--name-only", "--pretty=format:", commit.id], {
   #             silent: true
    #          }));
    #        const output = (await Promise.all(promises))
     #         .flatMap(m => m.stdout.split(/\r?\n/))
      #        .map(m => m.trim())
       #       .filter(f => f !== "");
        #    console.log(output);
         #   core.setOutput("files", JSON.stringify(output));
  update_contributors:
    name: Update contributors
    runs-on: ubuntu-latest
    needs: [get_all_files, update_translations]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      # Pulls the translation changes from above.
      - name: Pull changes
        run:
          git pull origin
      - name: Create local changes
        run: |
          cd .github/scripts/update-contributors
          node index.js ${{ github.actor }} ${{ join(fromJSON(needs.get_all_files.outputs.files), ' ') }}
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated contributors